FROM cr.yandex/mirror/library/golang:1.19-alpine

# Устанавливаем gcc и инструменты сборки
RUN apk add --no-cache build-base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .


CMD ["go", "test", "-v", "./..."]