services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: ".env"
    volumes:
      #- ./templates:/app/templates # unix
      - "./templates:/app/templates" # windows
    ports:
      - 8153:8153
    networks:
      - app





volumes:
  templates_data:
    name: templates_data

networks:
  app: