openapi: 3.0.0
info:
  description: This is Print Bram Space Client API
  version: 0.0.0
  title: Print Bram Space
  license:
    name: Bramtech company
servers:
  - url: http://example.domain/api
    description: Текущая без версии
tags:
  - name: templates
    description: Работа с шаблонами для печати
  - name: tags
    description: Работа с тэгами для печати
  - name: export
    description: Вывод на печать
paths:
  /db/get_all_templates:
    get:
      tags: 
        - templates
      summary: Получение получение всех шаблонов
      description: Получение получение всех шаблонов
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/ShortTemplate'
        
  /db/get_template:
    get:
      tags: 
        - templates
      summary: Получение получение шаблона по его id
      description: Получение получение шаблона по его id
      parameters:
        - name: id
          in: query
          schema: 
            type: integer
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '404':
          description: Шаблон не найден
        '422':
          description: Необходим  id шаблона
  /db/add_template:
    post:
      tags:
        - templates
      summary: Добавление шаблона
      description: Добавление/изменение шаблона
      requestBody: 
        content: 
          application/json:
            "schema":
              $ref: '#/components/schemas/AddTemplate'
      responses:
        '201':
          description: Шаблон добавлен
  /db/delete_template:
    delete:
      tags:
        - templates
      summary: Удаление шаблона
      description: Удаление шаблона
      parameters:
        - name: id
          in: query
          schema: 
            type: integer
      responses: 
        '204':
          description: Шаблон удален
        '404':
          description: Шаблон не найден
  /db/get_all_tags:
    get:
      tags:
        - tags
      summary: Получение всех тегов
      description: Получение всех тегов
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/ShortTag'
  /db/add_tag:
    post:
      tags:
        - tags
      summary: Добавление тэга
      description: Добавление/изменение тэга.
      requestBody: 
        content: 
          application/json:
            "schema":
              $ref: '#/components/schemas/AddTag'
      responses:
        '201':
          description: Тэг добавлен
  /db/delete_tag:
    delete:
      tags:
        - tags
      summary: Удаление тэга
      description: Удаление тэга
      parameters:
        - name: id
          in: query
          schema: 
            type: integer
      responses:
        '204':
          description: Тэг удален
        '404':
          description: Тэг не найден
  /export:
    post:
      tags:
        - export
      summary: Вывод на печать шаблона
      description: Вывод на печать шаблона
      requestBody: 
        content: 
          application/json:
            "schema":
              $ref: '#/components/schemas/ExportTemplate'
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '404':
          description: Шаблон не найден
components:
  schemas:
    Template:
      type: object
      properties:
          id:
            type: integer
          name:
            type: string
          content:
            type: string
    ShortTemplate:
      type: object
      properties:
          id:
            type: integer
          name:
            type: string
    AddTemplate:
      type: object
      properties:
          name:
            type: string
          content:
            type: string
    ShortTag:
      type: object
      properties:
          id:
            type: integer
          name:
            type: string
    AddTag:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        subsystem:
          type: string
        alias:
          type: string
    ExportTemplate:
      type: object
      properties: 
        template_id:
          type: integer
        data:
          type: object
      

    